sudo: false
language: ruby
rvm:
  - 2.4
  - ruby-head
matrix:
  include:
    - rvm: jruby-9.1.13.0
      jdk: openjdk8
    - rvm: jruby-9.1.13.0
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: openjdk8
    - rvm: jruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
before_install: gem install bundler
